### ISSUE TITLE
Problems using pyshtools with Spyder and Conda [OSX]

### ISSUE THREAD

**Issue by odeviron** [SHTOOLS/SHTOOLS#118]

**Comment by odeviron** [comment]
Hello,
I try to import the tool to spyder python3 on a mac. I got the following problem:
ImportError: dlopen(/Users/odeviron/anaconda3/lib/python3.6/site-packages/pyshtools/_SHTOOLS.cpython-36m-darwin.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Users/odeviron/anaconda3/lib/python3.6/site-packages/pyshtools/.dylibs/libgfortran.4.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/odeviron/anaconda3/lib/python3.6/site-packages/pyshtools/.dylibs/libgfortran.4.dylib

I looked on the web, and it was said that it can be solved using:
xcode-select --install
But it does not help.
 What can I do?
Thanks,
odv

**Comment by MarkWieczorek** [comment]
I just installed spyder on OSX, and pyshtools appears to work for me. I suspect that the problem is related to dependency problems when using conda (I don't use conda). 

As a quick fix, you might want to 

* try installing shtools from source as opposed to using the compiled binary (`pip3 install -no-binary pyshtools pyshtools`; yes, two times...).
* installing spyder by pip (`pip3 install spyder`), as opposed to using the conda version.

If conda is the problem, the obvious solution would be for us to build a conda package for pyshtools.

**Comment by MarkWieczorek** [comment]
Also, the conda-forge fftw library won't work with pyshtools. You will need to install fftw using:

`conda install --no-deps -c eumetsat fftw3`

**Comment by MarkWieczorek** [comment]
I am going to assume that you got this to work. If not, feel free to re-open this issue.
