### ISSUE TITLE
orthopy

### ISSUE THREAD

**Issue by nschloe** [SHTOOLS/SHTOOLS#202]
Hi everyone,

I'm wondering if [orthopy](https://github.com/nschloe/orthopy#sphere) (a project of mine) might be able to enhance SHTOOLS in some way. orthopy can evaluate complex-valued spherical harmonics _very_ fast; I'd like to benchmark it against against shtools. Any hints on how one could do that?

![f](https://user-images.githubusercontent.com/181628/67899993-bc3d9f80-fb63-11e9-874d-5b051f00faa1.png)

**Comment by MarkWieczorek** [comment]
If you would like to do some timing tests, here are some simple scripts that do this for shtools:

https://github.com/SHTOOLS/SHTOOLS/tree/master/examples/python/TimingAccuracy

**Comment by nschloe** [comment]
Can you point me to some code that shows how to _evaluate_ the spherical harmonics with SHTOOLS?

**Comment by MarkWieczorek** [comment]
You could start with the two introduction python notebooks.

https://shtools.oca.eu/shtools/public/python-examples.html

**Comment by nschloe** [comment]
Well, okay, I had expected that the most basic functionality would be the evaluation of spherical harmonics. Seems I'm out of my depth here. Closing.

**Comment by MarkWieczorek** [comment]
If you would have read the documentation, you would have found the following:

To evaluate the spherical harmonic coefficients `clm` on a global grid, use
```
clm.expand()
```
To evaluate the function at a specific point, use:

```
clm.expand(lat=xxx, lon=yyy)
```
If you want to time how long it takes to do this, see the example code that I already referred you to:

https://github.com/SHTOOLS/SHTOOLS/tree/master/examples/python/TimingAccuracy

Please let us know what you find with your comparisons. If you have a substantially faster way to do this for ultra-high-degrees, I would be very interested.

**Comment by nschloe** [comment]
I did read the documentation, I just don't understand enough to make any sense of it. One thing to note is probably that I'm coming from a different angle here; I'm a mathematician, and I'm looking at spherical harmonics as _functions_ that are evaluated at a number of points on a unit sphere.

Things that are probably perfectly obvious to geodesy people but not to me are what is meant by "evaluating coefficients" (as opposed to evaluating the function), and why the class [SHComplexCoeffs](https://shtools.github.io/SHTOOLS/python-shcoeffs.html) can be initialized "from" something. In my understanding, spherical harmonics don't have any input parameters (except perhaps the normalization, phase etc.). When trying to evaluate a spherical harmonic, I tried
```python
from pyshtools import SHCoeffs

x = SHCoeffs.from_zeros(5, kind='complex', normalization='ortho')
vals = x.expand(lat=[0.4, 0.1], lon=[0.5, 0.1])
print(vals)
```
```
[0j, 0j]
```
Like I said, I don't understand the `from` thing, and I don't know the first argument to `from_zeros` is. Anyhow, the `[0j, 0j]` is not what I would have expected.

**Comment by MarkWieczorek** [comment]
```

**Comment by MarkWieczorek** [comment]
`SHCoeffs.from_zeros` simply sets the spherical harmonic coefficients of a function equal to zero. There are several ways to initialize the spherical harmonic coefficients (such as by reading the values from a file).

The first argument `lmax` is simply the maximum spherical harmonic degree of the (bandlimited) function. 

The method `expand` determines the value of the function at the specified point.

Given that you set all the spherical harmonic coefficients equal to zero, the function will be zero, which is what you indeed find.

If you are going to use pyshtools, you should realize that the main point of the archive is to evaluate the function on a large number of equally spaced geographic grid nodesj. This is done quickly using FFTs (see the docs). Evaluating the function using your own specified latitudes and longitudes will be considerable slower.

Also, please note that I just found a bug in the `.expand()` method that only affect complex coefficients in version 4.5. I suspect that you are using an earlier version. The bug is simply related to a change in the python wrapper functions, and does not affect the original fortran code. The fix is on my personal github repo, and this will be merged into the develop branch next week.

I would suggest that you read the scientific article describing shtools. This code is written for geophysicists, astronomers, medical imaging, etc., and I realize that mathematicians probably have a different set of notations and conventions. It is quite likely that this code doesn't do what you want.
