### ISSUE TITLE
Problem in Fortran Compilation

### ISSUE THREAD

**Issue by HAMAMA-SAN** [SHTOOLS/SHTOOLS#233]
Dear sir,

I had. a problem in installing SHTOOLS during compilation I recieved this error :
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status

[root@localhost SHTOOLS-4.6]# gfortran -I/home/hamama/SH/SHTOOLS-4.6/modules -m64 -fPIC -O3 -std=f2003 -ffast-math -L/home/hamama/SH/SHTOOLS-4.6/lib -lSHTOOLS -L/usr/local/lib -lfftw3 -lm -llapack -lblas
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status

can you help me?

**Comment by MarkWieczorek** [comment]
Could you let me know if you are having problems compiling the shtools archive, or if you are having problems compiling your own program?

If it is the first, could you give me the command you are using to compile the archive, and provide more output so that I can understand what is going on?

If you are just trying to compile your own problem: It appears that you probably just forgot to add your program name to  command.

**Comment by HAMAMA-SAN** [comment]
![Screen Shot 2020-07-02 at 16 28 45](https://user-images.githubusercontent.com/49543242/86329566-4dc85880-bc81-11ea-8b4f-cb9d675342dd.jpg)
![Screen Shot 2020-07-02 at 16 29 15](https://user-images.githubusercontent.com/49543242/86329585-5456d000-bc81-11ea-9c48-55ef83375897.jpg)
I just was installing SHTOOLS because it is one of needed package for  another package.

**Comment by MarkWieczorek** [comment]
It appears that the shtools archive compiled perfectly fine. 

Could you let me know why you are entering the command after you successfully compiled the archive? You would only use that command if you have your own fortran program that you are compiling. And if you use that command, you obviously need to add the name of the fortran file at the end.

**Comment by HAMAMA-SAN** [comment]
Thanks a lot for your quick reply. I got it 
sorry for miss understanding

**Comment by MarkWieczorek** [comment]
No problem.
