### ISSUE TITLE
How to extract EGM2008 data in expected format

### ISSUE THREAD

**Issue by paddyroddy** [SHTOOLS/SHTOOLS#275]
I would like to use some inbuilt in datasets in `pyshtools.datasets` but to make sure I'm using it correctly I'm trying `pyshtools.datasets.Earth.EGM2008()` that I already use.

The dataset that I was already using is the `Coeff_Height_and_Depth_to2190_DTM2006.0.gz` data from https://earth-info.nga.mil/GandG/wgs84/gravitymod/egm2008/first_release.html. I've read this in and converted to harmonic components where the first 9 look like (setting -ve `m` to zero)
```
-2382.09242595 + 0.j, (ell=0, m=0)
 0. + 0.j, (ell=1, m=-1)
650.00975919 + 0.j, (ell=1, m=0)
602.21739892 + 401.91939816j, (ell=1, m=1)
 0. + 0.j, (ell=2, m=-2)
 0. + 0.j, (ell=2, m=-1)
569.27982613 + 0.j, (ell=2, m=0)
331.14299745 + 314.1576337j, (ell=2, m=1)
-419.29542895 - 82.20926462j, (ell=2, m=2)
```

I'm using orthonormal & complex spherical harmonics with phase convention `f_(l m)^* = (-1)^m f_(l -m)`.

I'm not sure what format `flm = pyshtools.datasets.Earth.EGM2008()` returns, I can see the shape of `flm.coeffs` is `(2, 2191, 2191)` but how I do I get similar numbers to what I'm expecting?

This may be related to #274 which includes the harmonic transform codes I'm using

**Comment by MarkWieczorek** [comment]
> I'm not sure what format `flm = pyshtools.datasets.Earth.EGM2008()` returns, I can see the shape of `flm.coeffs` is `(2, 2191, 2191)` but how I do I get similar numbers to what I'm expecting?

The simple answer is: Every gravity field model that I am aware of uses real harmonics that are 4pi normalized and that exclude the (-1)^m phase factor.

In general, if you want to know what the normalization of a given dataset is, just do the following:

```
In [2]: flm = pysh.datasets.Earth.EGM2008()

In [3]: flm.info()
kind = 'real'
normalization = '4pi'
csphase = 1
lmax = 2190
GM (m3 / s2) = 398600441500000.0
r0 (m) = 6378136.3
Omega (rad / s) = 7.292115e-05
error_kind = 'calibrated'
header = None
header2 = None
name = 'EGM2008'
epoch = None
```
To convert the coefficients to a different normalization, use the methods `flm.convert()` or `flm.to_array()` along with the parameters `normalization` and `csphase`.

In general, the `SHGravCoeffs` subclass doesn't deal with imaginary coefficients, because all gravity models use real 4pi coefficients. If you *really* need imaginary coeffcients, you could export the coefficients, read them into a new `SHCoeffs` class, and then convert them to imaginary:
```
coeffs = flm.to_array(normalization='4pi', csphase=1)
clm = pysh.SHCoeffs.from_array(coeffs, normalization='4pi', csphase=1)
clm_complex = clm.convert(kind='complex', normalization='ortho', csphase=-1)
```
Hope this helps.

**Comment by paddyroddy** [comment]
Okay, well the code I'm using requires matrices to be complex, so I do need the imaginary components.

Thanks for your suggestion but using that I still cannot recreate the `flm` values I was anticipating

**Comment by MarkWieczorek** [comment]
I see what your problem is now.

`Coeff_Height_and_Depth_to2190_DTM2006.0.gz` is not a gravity field and is not `EGM08`: It is the elevation of the Earth above mean sea level. You should be using the file `EGM2008_to2190_TideFree.gz` (or `EGM2008_to2190_ZeroTide.gz`).

**Comment by paddyroddy** [comment]
ah yes I'd just come to the same conclusion, apologies for the confusion. I just tried `pysh.datasets.Earth.Earth2014.tbi()` is similar to the data I was expecting (although of course it is `real`, and different normalisation/phase)
