### ISSUE TITLE
SHExpandSLQ Support for Hemisphere model？

### ISSUE THREAD

**Issue by wow-yes** [SHTOOLS/SHTOOLS#276]
**Description of the problem**

How to apply SHExpandSLQ  for a Hemisphere model? Our data only contains the south hermisphere part.

Thanks.

**System information**

**Comment by MarkWieczorek** [comment]
Was there a problem when you used this routine to determine the spherical harmonic coefficients? Since you have no data over one hemisphere, you shouldn't expect the interpolation over the hemisphere with no to give realistic results. 

One option would be to apply a regularisation constraint in the least-squares inversion. This shouldn't be hard to do, but you would have to modify the Fortran code.

**Comment by MarkWieczorek** [comment]
I am going to close this issue. If you have any additional problems, please feel free to re-open it.
