### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by spacefan** [SHTOOLS/SHTOOLS#286]
## Description of the problem

When I execute the following code:

```python
#!/usr/bin/python
# -*- coding: UTF-8 -*-

import pyshtools as pysh
pysh.datasets.Earth.XGM2019E(lmax=2190)
```

SHTOOL throws the following error:

```python
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-49-782dd822c416> in <module>
      5 #earth_GrvGOCO06S    = pysh.datasets.Earth.GOCO06S()#(lmax=300)
      6 #earth_GrvEIGEN_RL04 = pysh.datasets.Earth.EIGEN_GRGS_RL04_MEAN_FIELD(epoch=20201231, lmax=300)
----> 7 pysh.datasets.Earth.XGM2019E(lmax=2190)

C:\Miniconda3\lib\site-packages\pyshtools\datasets\Earth\__init__.py in XGM2019E(lmax)
    213         path=_os_cache('pyshtools'),
    214     )
--> 215     return _SHGravCoeffs.from_file(fname, lmax=lmax, format='icgem',
    216                                    errors='formal', omega=_egm2008.omega.value,
    217                                    name='XGM2019E')

C:\Miniconda3\lib\site-packages\pyshtools\shclasses\shgravcoeffs.py in from_file(self, fname, format, gm, r0, omega, lmax, normalization, skip, header, header2, errors, error_kind, csphase, r0_index, gm_index, omega_index, header_units, set_degree0, name, epoch, encoding, **kwargs)
    625                                                  encoding=encoding)
    626             elif errors in valid_err:
--> 627                 coeffs, gm, r0, error_coeffs = _read_icgem_gfc(
    628                     filename=fname, errors=errors, lmax=lmax, epoch=epoch,
    629                     encoding=encoding)

C:\Miniconda3\lib\site-packages\pyshtools\shio\icgem.py in read_icgem_gfc(filename, errors, lmax, epoch, encoding)
     88 
     89     with f:
---> 90         for line in f:
     91             if 'end_of_head' in line:
     92                 break

UnicodeDecodeError: 'gbk' codec can't decode byte 0x99 in position 615: illegal multibyte sequence
```

## System information

OS: `Windows 10, Chinese Language`
Python: `Python 3.8.6`
SHTOOL: `4.8`

**Comment by MarkWieczorek** [comment]
This works on my macOS machine, so could you try a couple of things for me?

* First, please make sure that you have latest version of pooch installed. If this is the problem, it would be great if you could tell me which version you were using so I can update the minimum version required.
* Second, could you try reading a few models that come from the same web site, like "GOCO06S", and "EGM2008"?
* Lastly, try loading the coefficients this way:
```
fname ="http://icgem.gfz-potsdam.de/getmodel/gfc/eeb03971cf6e533e6eeb6b010336463286dcda0846684248d5530acf8e800055/XGM2019e_2159.gfc"
clm = pysh.SHGravCoeffs.from_file(fname, lmax=2190, format='icgem', errors='formal', name='XGM2019E')
```

**Comment by QuLogic** [comment]
The doc for `.from_file` (and very many other places) says the default encoding is utf-8, but the signature uses `encoding=None`. That doesn't use utf-8 by default, it uses the system default encoding. In this case, the system is set to Chinese, so the encoding is gbk.

**Comment by MarkWieczorek** [comment]
Thanks @QuLogic . I never considered the possibility that the default encoding wasn't utf-8. There are a few routines for reading text-based spherical harmonic files, so maybe I should make sure that each of these has an `encoding` argument, and then set the default to `utf-8`. Or is there a better approach?

**Comment by QuLogic** [comment]
If you (or some standard) created the files with a specific encoding, it's best to pass that explicitly. I think `utf-8` should be the default, but Windows has a long history of other encodings, so passing an encoding when you know for sure what it is is best.

**Comment by spacefan** [comment]
> This works on my macOS machine, so could you try a couple of things for me?
> 
> * First, please make sure that you have latest version of pooch installed. If this is the problem, it would be great if you could tell me which version you were using so I can update the minimum version required.
> * Second, could you try reading a few models that come from the same web site, like "GOCO06S", and "EGM2008"?
> * Lastly, try loading the coefficients this way:
> 
> ```
> fname ="http://icgem.gfz-potsdam.de/getmodel/gfc/eeb03971cf6e533e6eeb6b010336463286dcda0846684248d5530acf8e800055/XGM2019e_2159.gfc"
> clm = pysh.SHGravCoeffs.from_file(fname, lmax=2190, format='icgem', errors='formal', name='XGM2019E')
> ```

- My pooch version is 1.3.0, which is latest release;
- Other gravity models like "GOCO06S" and "EGM2008 is ok, except XGM2019E;
- The last way works fine for me:

```python
fname ="http://icgem.gfz-potsdam.de/getmodel/gfc/eeb03971cf6e533e6eeb6b010336463286dcda0846684248d5530acf8e800055/XGM2019e_2159.gfc"
clm = pysh.SHGravCoeffs.from_file(fname, lmax=2190, format='icgem', errors='formal', name='XGM2019E')
print(clm)

kind = 'real'
normalization = '4pi'
csphase = 1
lmax = 2190
GM (m3 / s2) = 398600441500000.0
r0 (m) = 6378136.3
Omega (rad / s) = None
error_kind = 'formal'
header = None
header2 = None
name = 'XGM2019E'
epoch = None
```

**Comment by MarkWieczorek** [comment]
Now I am confused. `pysh.datasets.Earth.XGM2019E()` is simply this code:
```
    fname = _retrieve(
        url="http://icgem.gfz-potsdam.de/getmodel/gfc/eeb03971cf6e533e6eeb6b010336463286dcda0846684248d5530acf8e800055/XGM2019e_2159.gfc",  # noqa: E501
        known_hash="sha256:ee24f7cf68f45b44cdbf3ccbf57e7382c7667869356061419f00f2ca951861e4",  # noqa: E501
        downloader=_HTTPDownloader(progressbar=True),
        path=_os_cache('pyshtools'),
    )
    return _SHGravCoeffs.from_file(fname, lmax=lmax, format='icgem',
                                   errors='formal', omega=_egm2008.omega.value,
                                   name='XGM2019E')

```
In the first command, Pooch downloads the file and returns the path of the file. In the second command, `SHGravCoeffs.from_file` reads the file (using `read_icgem_gfc`).

The file encoding is not set in the `datasets` function, and because of this, it doesn't work. However, when you use the separate commands, it *does* work. Furthermore, this works fine when downloading GOCO06S and EGM2008, which are from the same website, and which use the exact commands as above for XGM2019E.

**Comment by MarkWieczorek** [comment]
I think I know what is going on now, but I don't have the solution. The original error mentions position 615 in the file, and this corresponds to the single  quotation mark.

<img width="36" alt="Screen Shot 2021-01-29 at 10 46 00" src="https://user-images.githubusercontent.com/8697285/106259223-381f0f80-621f-11eb-9260-f2735e559210.png">

I'm pretty sure that this is not a utf-8 character. I am confused though, because my python default is to use utf-8 and my system can read the file fine. Is this utf-16? I could easily force the dataset command to use the correct encoding, but I would like to know what that is before making the change!

**Comment by MarkWieczorek** [comment]
I fixed this issue in this PR: https://github.com/SHTOOLS/SHTOOLS/pull/288.

In essence, when using the requests package to download from a url, it guesses that the encoding is utf-8. However, when reading from a file, the open statement uses the default system encoding. The fix was to add an encoding option to all the read/write functions, and then hardcode utf-8 into the datasets. It would be great if you could test it for me.

Most likely, I will put out a minor release in the next two weeks to fix this.

**Comment by spacefan** [comment]
Great, problem solved, now the output is normal, show as follows:

```python
>>> pysh.datasets.Earth.XGM2019E(lmax=2190)

kind = 'real'
normalization = '4pi'
csphase = 1
lmax = 2190
GM (m3 / s2) = 398600441500000.0
r0 (m) = 6378136.3
Omega (rad / s) = 7.292115e-05
error_kind = 'formal'
header = None
header2 = None
name = 'XGM2019E'
epoch = None
```

Issue closed.
