### ISSUE TITLE
Theta gradients at the poles

### ISSUE THREAD

**Issue by mreineck** [SHTOOLS/SHTOOLS#301]
As far as I understand, gradient maps generated by SHTOOLS always have zeros for rings at the poles, both the derivatives in phi and in theta direction. While for phi the values are more or less arbitrary (since the dphi element is zero at a pole), for the theta part this doesn't appear so obvious to me. It's perfectly possible to have a function on the sphere which is increasing or decreasing along a meridian while it crosses a pole.
For compatibility, I'm currently zeroing these rings when computing the gradients with `ducc`, but I wonder whether it might be better to change the SHTOOLS behavior here.

**Comment by wczrk** [comment]
The problem is that the gradient has a term that is 1/sin(theta). It is possible that when you multiply this by the derivative of the Legendre functions that the 1/0 term factors out. You'll need to show me the derivation or give me a reference if you want this changed. I just set it to zero because not many people are going to be concerned by the poles given this singularity. I think that Generalized Spherical Harmonic functions might deal with this case better, but it has been a while since I looked into those.

**Comment by mreineck** [comment]
I think I'm avoiding this singularity in `ducc0` by using spin-1 spherical harmonic transforms, but I have not looked any deeper into it yet. In any case I agree with you: the potential gain is low, and the effort of adjusting the low-level routines in SHTOOLS would be pretty high. Not need to look into this, at least not with any priority
