### ISSUE TITLE
Sign of latitude gravity acceleration (2nd component)

### ISSUE THREAD

**Issue by VitalianoGentile** [SHTOOLS/SHTOOLS#324]
Hello everyone. I have encountered a sign discordance in the second component of the gravity acceleration when using the 'gravmag.MakeGravGridPoint' command.
In particular I compared the output of this command with the output of Matlab. Matlab calculates the accelerations in Cartesian coordinates using the command 'gravitysphericalharmonics' and through the command 'cart2sphvec' it is possible to report these accelerations in spherical coordinates.
I have compared the two attached codes, you can see that the values of the outputs are consistent with each other, except for the sign of the second component (latitudinal acceleration).
Is there a problem or am I missing something?

Is it possible that the problem is the follow line of code? 
https://github.com/SHTOOLS/SHTOOLS/blob/8d83c42d1313d5624c4db8c2e57300c5d819834e/src/MakeGravGridPoint.f95#L79

Output of gravmag.MakeGravGridPoint (Python):

radial_acceleration =  - 8.141684046873648 m/s^2
lat_acceleration      =    2.196891979539819e-04 m/s^2
lon_acceleration     = - 3.91036885306263e-05 m/s^2

Output of gravitysphericalharmonics (Matlab, in spherical coordinates):

radial_acceleration = - 8.141684043835372 m/s^2
lat_acceleration      = - 2.196891977902099e-4 m/s^2
lon_acceleration     = - 3.910368850149060e-05 m/s^2

[gravitysphericalharmonic.txt](https://github.com/SHTOOLS/SHTOOLS/files/7568780/gravitysphericalharmonic.txt)
[gravmag.MakeGravGridPoint.txt](https://github.com/SHTOOLS/SHTOOLS/files/7568781/gravmag.MakeGravGridPoint.txt)

Thanks for the great work done!

**Comment by MarkWieczorek** [comment]
Hi. I suspect that this is just of problem of not understanding what coordinate system the two codes are using. In the shtools gravity routines, the documentation says 

> The input latitude and longitude are in degrees, and the output components of the gravity are in spherical coordinates (r, theta, phi)

So what you are calling "lat_accelation", is actually the acceleration in the theta-hat direction. Theta is the angle from the north pole, and points towards the south pole. I suspect that the other code you are comparing to uses the (radial, north, east) coordinates. Another thing to be aware is that for both codes, the coordinate system is not perpendicular to the ellipsoid.

If this is indeed the case, I'd be interested in how I could improve the documentation so that others don't run into the same problem.

**Comment by VitalianoGentile** [comment]
Thanks for the reply, I checked the calculations and I think the problem is that I considered theta as starting from the equator and going north, that is in the opposite direction. I was confused by this sentence in the:

> Returns
> value : float, dimension (3)
> Vector components (r, theta, phi) of the gravity at (r, lat, lon).

I thought the output was in the same order as the inputs and so (r, lat, lon), where 'lat' started from the equator.

Thanks again for the reply.
