### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by zap150** [SHTOOLS/SHTOOLS#334]
**Description of the problem**

SHTOOLS presents itself as BSD-3 library. However, it links againts FFTW3, which is a copyleft GPL-2 library. What am I  missing here?

**Comment by zap150** [comment]
As far as I know, you cannot distribute anything linking against GPL code as anything other than GPL. For LGPL this should not be an issue, if you link dynamically.

**Comment by mreineck** [comment]
> As far as I know, you cannot distribute anything linking against GPL code as anything other than GPL.

This is not exactly correct. It's true that have to give the recipient of your code the choice to accept it under GPL, but you can also add other choices. And since distribution under BSD-3 gives the recipient the choice to accept the code under GPL terms (i.e. BSD-3 is more liberal than GPL), this is fine.

This combination of licenses is not uncommon. Some projects deliberately decide against it (since it makes using the project in commercial software difficult or impossible), but this is a policy decision, and not due to an intrinsic conflict.

**Comment by MarkWieczorek** [comment]
I should add that shtools/pyshtools does not require FFTW3: you could swap this out and use MKL instead (which has an identical api, but a different license). Also, this github archive doesn't *distribute* anything. It is up to the user to complile the source and choose to link to fftw3 if they want to or not, taking into account any issues there may be with licensing.

The pip and conda installs do, however, link to the FFTW3 pip/conda packages, and I think that this is your concern. We had a discussion about changing the license for the conda package [here](https://github.com/conda-forge/pyshtools-feedstock/issues/3). As you can see, there was no clear resolution.

I am not a lawyer, and every time I search on this subject, I never get a clear answer. Different people give me different answers. If you could provide a few authoritative links on this, I would be happy to look into this again. In any case, if you are simply worried, I did talk to the fftw3 people a while ago, and they don't seem to care. They wrote a very long email that explained how it is complicated. This, however, is not an excuse for using in improper license (if that is indeed the case). It is just that I am an academic researcher maintaining this repo for free. I have no funding to hire a lawyer to figure this out and the community here has never given me a clear answer one way of the other.

**Comment by MarkWieczorek** [comment]
I am going to close this issue. If there is something that still needs to be addressed or clarified, please feel free to re-open it.
