### ISSUE TITLE
ducc0 does not support grids of booleans

### ISSUE THREAD

**Issue by MarkWieczorek** [SHTOOLS/SHTOOLS#336]
The DUCC0 spherical harmonic transforms (no longer) appear to support grids that are composed of booleans. I am pretty certain that this worked in the past, but after updating to the most recent version of ducc0, one of the notebooks would no longer compile (`localized-spectral-analysis.ipynb`).

Here is a quick demonstration:

```
In [79]: z = pysh.SHGrid.from_zeros(lmax=2)

In [80]: z.data = z.data.astype('bool')

In [81]: z.expand()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-81-b1960bb5901f> in <module>
----> 1 z.expand()

~/SphericalHarmonics/shtools/pyshtools/shclasses/shgrid.py in expand(self, normalization, csphase, lmax_calc, backend, nthreads)
   1012             backend = preferred_backend()
   1013
-> 1014         return self._expand(normalization=normalization, csphase=csphase,
   1015                             lmax_calc=lmax_calc, backend=backend,
   1016                             nthreads=nthreads)

~/SphericalHarmonics/shtools/pyshtools/shclasses/shgrid.py in _expand(self, normalization, csphase, lmax_calc, backend, nthreads)
   1872                 )
   1873
-> 1874         cilm = backend_module(
   1875             backend=backend, nthreads=nthreads).SHExpandDH(
   1876                 self.data[:self.nlat-self.extend, :self.nlon-self.extend],

~/SphericalHarmonics/shtools/pyshtools/backends/ducc0_wrapper.py in SHExpandDH(grid, norm, sampling, csphase, lmax_calc)
    353     if lmax_calc > (grid.shape[0] // 2 - 1):
    354         raise RuntimeError("lmax_calc too high")
--> 355     alm = _analyze_DH(grid, lmax_calc)
    356     return _extract_alm(alm, lmax_calc, norm, csphase)
    357

~/SphericalHarmonics/shtools/pyshtools/backends/ducc0_wrapper.py in _analyze_DH(map, lmax)
    175
    176 def _analyze_DH(map, lmax):
--> 177     alm = ducc0.sht.experimental.analysis_2d(
    178         map=map.reshape((1, map.shape[0], map.shape[1])),
    179         spin=0,

RuntimeError:
./python/sht_pymod.cc: 544 (py::array ducc0::detail_pymodule_sht::Py_analysis_2d(const py::array &, size_t, size_t, const std::__1::string &, py::object &, size_t, py::object &)):

type matching failed: 'alm' has neither type 'c8' nor 'c16'
```

There are two possible ways of solving this. First in the pyshtools code, we could check to see if the grid is composed of bools, and then convert it to integers (or floats). However, given that the shtools backend handles this case, it would probably be best to simply modify the ducc0 wrappers (or ducc0 itself), to deal with this case.

**Comment by mreineck** [comment]
Hmm, if this ever worked in the past, I'd be really surprised - and I'd argue that it was a bug :-)

The only data types I would expect to see on the interface are (as described in the ducc0 docstrings) `float32` or `float64` for maps, and `complex64` or `complex128` for spherical harmonic coefficients, and the "accuracy" of the output type always matches the input type. With boolean or integer inputs this cannot be done.

I can add automatic conversion of input grids to the wrapper, but there are some questions (e.g. which floating point accuracy should be used), and I'm not sure we are doing the user a favour by allowing this, since such a call will (ar least in my experience) almost always be a mistake and should be warned about.

Also this introduces an asymmetry between the expansion of grids (which can be boolean/integer) and expansion of spherical haronic coefficients (which cannot be, since there is no "int complex" or "bool complex" in `numpy`).

**Comment by MarkWieczorek** [comment]
The rational for accepting bools is that they are used when making masks for the localized spectral analyses. In the f95 shtools code, these get automatically upgraded to double. In `SHGrid.from_array()`, I could just add a check to see if the  arrays is bool, and then upgrade it via `data.astype(float)`

**Comment by mreineck** [comment]
My worry is that an expansion of any integer (and especially boolean) will result in not very useful coefficients, because the grid is clearly not band limited (except for the trivial case where the input grid has completely uniform value). So if you expand the resulting coefficients back onto a grid, you will get something quite different from the input grid.

In any case, I have prepared a PR that should work (#337). Please give it a try!

**Comment by MarkWieczorek** [comment]
I guess that this is a difference between fortran and C (or the way the backends are implemented). If you send an array of boleans or integers to a fortran subroutine that expects a double, then it automatically gets converted to double. The fortran routines do everything using double precision, so there really isn't much ambiguity there. However, if ducc can either use float32 or float64 then I could see why this might be problematic. 

However, in order that the shtools and ducc backends be consistent, maybe we should always use float64/complex128 ?

**Comment by mreineck** [comment]
It's possible to achieve the same effect (always convert to some desired data type) with the `pybind11` interface as well. I decided not to use this, because single-precision input/output may be sufficient in many situations, and every implicit conversion of an array adds memory overhead, which can become a real show-stopper in some situations.
You are right that for consistency's sake we should always use double precision in the ducc backend. I'll update the PR accordingly.

**Comment by MarkWieczorek** [comment]
This is probably the easiest solution for now, but I agree that if single precision is enough, and memory is an issue, then you should be allowed to do that. Not sure how this could be standardized with the shtools backend though. We could just write in the docs that shtools is always float64, but that ducc0 uses the precision of the input, but I just see this causing problems. Let me think about this over the weekend...
