### ISSUE TITLE
Missing shtools.mod on macOS

### ISSUE THREAD

**Issue by maedoc** [SHTOOLS/SHTOOLS#348]
**Description of the problem**
I've git cloned the repo at tag v4.9.1 and tried to `python setup.py build_ext` and compilation seems to go well until building `src/PythonWrapper.f95`:

```
compile options: '-DSCIPY_FFTW3_H -DNO_ATLAS_INFO=3 -DHAVE_CBLAS -Ibuild/temp.macosx-11.0-arm64-3.8 -I/Users/duke/miniforge3/envs/tfp/include -Ibuild/src.macosx-11.0-arm64-3.8/build/src.macosx-11.0-arm64-3.8/src -I/Users/duke/miniforge3/envs/tfp/lib/python3.8/site-packages/numpy/core/include -Ibuild/src.macosx-11.0-arm64-3.8/numpy/distutils/include -I/Users/duke/miniforge3/envs/tfp/include/python3.8 -c'
gfortran:f90: src/PythonWrapper.f95
f951: Warning: Nonexistent include directory 'build/temp.macosx-11.0-arm64-3.8' [-Wmissing-include-dirs]
src/PythonWrapper.f95:2:13:

    2 |         use shtools, only: PlmBar
      |             1
Fatal Error: Cannot open module file 'shtools.mod' for reading at (1): No such file or directory
compilation terminated.
```

I noticed the compile options seem to include the wrong path (namely `build/temp.macosx-11.0-arm64-3.8`) to the `shtools.mod` file, 

```
$ find . -name shtools.mod                       
./build/temp.macosx-11.0-arm64-cpython-38/shtools.mod
```
but I don't know enough about distutils to understand why the wrong include path is happening.

**System information**

I'm using a conda Python environment on arm64 on macOS.  I can post other debug output on request.

**Comment by MarkWieczorek** [comment]
We just fixed this problem a couple of days ago.... You can either:

1. Downgrade setuptools to version 62.0.0. The latest version 62.1.0 has a breaking change.
2. Switch to the `develop` branch. We modified the setup.py file to work with 62.1.0. This will be merged into master in about 2 days (we are trying to fix some conda packaging issues beforehand, but if they aren't fixed by then, so be it...).
3. Wait ~2-3 days for the next release!

**Comment by maedoc** [comment]
ah ok thanks!
