### ISSUE TITLE
Sampling is incorrectly set when using DHRealGrid() class. 

### ISSUE THREAD

**Issue by ij264** [SHTOOLS/SHTOOLS#416]
**Description of the problem**
I was trying to use SHGrid.from_array() to read in a global set of grid data, but got this error: 
![Screenshot from 2024-01-10 11-00-23](https://github.com/SHTOOLS/SHTOOLS/assets/67367495/68112dca-a7c2-4b68-8a5f-b60804c3f0ff)
nlat = 91, nlon = 182, which is twice nlat, so I don't see how the error is correct.

**Comment by ij264** [comment]
When I dug into the DHRealGrid class, in the initialisation, there is this line of code:
```
 if self.nlon == 2 * self.nlat - self.extend:
            self.sampling = 2
```
Should it be: 
```
 if self.nlon == 2 * (self.nlat - self.extend:)
            self.sampling = 2
```
?

**Comment by MarkWieczorek** [comment]
I'm pretty sure that this is correct.

For DH grids with extend=False, nlat and nlon both are even. nlat is equal to N, which is equal to 2L+2. The size of the array is either NxN or Nx2N.

Since your input grid has nlat=91, this means that you are using grids with extend=True, which includes the redundant values at 360 E longitude and 90 S. For this case, nlat = N+1, and nlon is either N+1 or 2N+1. Thus the input nlon should be either 91 or 181. 

Since your input grid doesn't conform to these rules, it isn't a valid grid that can be used with the Driscoll and Healy quadrature routine.
