### ISSUE TITLE
Difference in Reconstruction

### ISSUE THREAD

**Issue by jehosafatc** [SHTOOLS/SHTOOLS#488]
**Description of the problem**
Hi - I just wanted to understand better the reason behind such a big difference when doing a reconstruction of a grid from the spherical harmonics. Code used:

import numpy as np
import pyshtools as pysh

grid = np.random.rand(180,360)
grid_data = pysh.SHGrid.from_array(grid)
clm = grid_data.expand()
recon = pysh.expand.MakeGridDH(clm.coeffs, sampling=2)
diff = grid - recon

**Comment by MarkWieczorek** [comment]
Hi there. First, instead of the command for `recon`, you could just use `recon = clm.expand()`. That way you don't need to specify the grid type and optional parameters.

As for your question:

For DH grids that are N by N in shape, the transforms are exact for a function that is bandlimited to degree N/2 -1. For DH2 grids, which have a size of 2N by N, the extra points in longitude in some sense aren't necessary, and the function is oversampled if you only want spherical harmonic degrees up to N/2-1.

In the spherical harmonic transformation routines, we use FFTs in longitude. For DH grids, we use all of the fourier coefficients. However, for DH2 grids, we throw out half of the coefficients that have angular orders greater than N/2-1. Because of this, when you reconstruct the grid from the spherical harmonic coefficients for this case you don't get the same result. The output grid is bandlimited to degree N/2-1, but the input grid is in some sense not well formed, and has an effective resolution that is greater than this (at least in longitude).

There is not much you can do about this. In creating DH2 grids, you could try to ensure that that it is banlimited to degree N/2-1 by some preprocessing. You could also resample the input grid so that it had a size of 2N by 2N. You could also consider resampling the data to use a GLQ grid.

This is described a little in the online documentation: https://shtools.github.io/SHTOOLS/grid-formats.html

I copy the relevant paragraphs here. If you think that the documentation needs to be updated, I'm open to suggestions. Or just open a PR!

> The second type of grid is for data that are sampled on regular grids. As shown by Driscoll and Healy [1994], an exact quadrature exists when the function f is sampled at N equally spaced nodes in latitude and N equally spaced nodes in longitude. For this sampling (DH), the grids make use of the longitude band at 90∘ N, but not 90∘ S, and the number of samples is 2(L+1), which is always even. Given that the sampling in latitude was imposed a priori, these grids contain almost twice as many samples in latitude as the grids used with Gauss-Legendre quadrature. It should be noted that for this quadrature, the longitude band at 90∘N is ultimately downweighted to zero, and hence has no influence on the returned spherical harmonic coefficients.

> For geographic data, it is common to work with grids that are equally spaced in degrees latitude and longitude. pyshtools provides the option of using grids of size N×2N, and when performing the Fourier transforms for this case (DH2), the coefficients clm and slm with m>L are discarded. The redundant data points at 360∘ E longitude and the latitudinal band at 90∘S are not required by the spherical harmonic transformation routines, but can be computed by specifying the optional argument extend.

**Comment by jehosafatc** [comment]
Hi thanks alot for this explanation. I have one last question, I did try as well do define the grid as:
grid = np.random.rand(180,180)
for some testing and then reconstructing different points using:
MakeGridPoint(clm, lat, lon)
This however, still did not give me good results. In fact it gave me things that were a huge percent error off the original grid. Is there a reason for this? 

-Thank you so much!

**Comment by MarkWieczorek** [comment]
Could you provide a short script so that I can reproduce the problem?

**Comment by jehosafatc** [comment]
Yes, 

import numpy as np
import pyshtools as pysh

grid = np.random.rand(180,180)
grid_data = pysh.SHGrid.from_array(grid)
clm = grid_data.expand()
recon = pysh.expand.MakeGridDH(clm.coeffs)
point = MakeGridPoint(clm.coeffs, 90, 0)
print(grid[0,0], point )

**Comment by MarkWieczorek** [comment]
> It should be noted that for this quadrature, the longitude band at 90∘N is ultimately downweighted to zero, and hence has no influence on the returned spherical harmonic coefficients.

Could you try a different latitude that isn't 90 or -90? Also, note that your input grid at 90 N has different values for different longitudes, which isn't possible in reality.

**Comment by mreineck** [comment]
I think the problem is that the initial random `grid` array is simply not band limited. Going from there to spherical harmonic coefficients and back to real space again is practically guaranteed to produce a result that's very different from the input.

**Comment by jehosafatc** [comment]
How would I make it band limited? Or maybe provide me an example that yields identical results for me to compare? So sorry, for all the questions just really stuck on my side of things.

**Comment by jehosafatc** [comment]
> > It should be noted that for this quadrature, the longitude band at 90∘N is ultimately downweighted to zero, and hence has no influence on the returned spherical harmonic coefficients.
> 
> Could you try a different latitude that isn't 90 or -90? Also, note that your input grid at 90 N has different values for different longitudes, which isn't possible in reality.

With some weather data it is possible to have different values for different longitudes. Even some models are very sporadic in the sense that they somewhat resemble a random grid per-se so I wanted to check if there was any way to maybe smooth the data or something similar that would yield the same result reconstructing it from SH

**Comment by MarkWieczorek** [comment]
One way would be to simply ignore the reconstructed values at 90 N and 90 S, as these are not used when computing the spherical harmonic coefficients. I will try to clarify the documentation regarding that point.

The other way would be to attack this problem from the other direction: Create a set of spherical harmonic coefficients first, and then compute the grid. This way you are ensured that it will be bandlimited.

And a more convenient way to evaluate the function at a grid point is to use `clm.expand(lat=x, lon=y)`. This way you don't need to keep track of the normalization conventions

**Comment by jehosafatc** [comment]
How would you go about creating the coefficients first without knowing the values for the grid at the different lat and lon?

**Comment by MarkWieczorek** [comment]
In your case, just ignore 90 S and 90 N. These two points on the sphere aren't used in the transformation from grid to coefficients.

**Comment by mreineck** [comment]
This won't solve the noninvertibility problem. At best it will look slightly less worse :(

**Comment by jehosafatc** [comment]
> This won't solve the noninvertibility problem. At best it will look slightly less bad :(

Thats correct, is there anything else to try or this just means the data is not suitable to be approximated by coefficients?

**Comment by mreineck** [comment]
Purely random values on a grid on the sphere will almost never have a valid representation as harmonic coefficients ... that's a quite nasty property of spherical geometry. You can see this from the fact that the transformation matrix between grid and spherical harmonics is not square, and so can by definition not be invertible. In most cases the number of pixels is higher than the number of spherical harmonic coefficients, so information is lost in the direction from map to coefficients.
