### ISSUE TITLE
Failed to install pySHTools on Windows

### ISSUE THREAD

**Issue by De-Guo** [SHTOOLS/SHTOOLS#62]
I try to install SHTOOLS on my 64 bit Windows 7, but all my trials have been ended up with failure.
I use 64 bit Anaconda 4.1.1, with the python version of 3.5.2.
The MinGW is installed as my fortran compiler. 
When I use 'pip install pyshtools', my python will stop working after a while,  alerting 'Python has stopped working'

**Comment by ioshchepkov** [comment]
Can you try to use pip in the verbose mode 

`pip install -V pyshtools `

and bring the output here?

If it will fail too without any output, then try to use `make` (read first the [Makefile](https://github.com/SHTOOLS/SHTOOLS/blob/master/Makefile)) command:

`make fortran`
`make python`

**Comment by dijun-g** [comment]
**Here is the the process of run 
`pip install -V pyshtools`
I'm sorry the following contents are of so large, because I have put every output here.**

# It says my python has stopped working after showing the following information
C:\Users\***>pip install -v pyshtools
Collecting pyshtools
  1 location(s) to search for versions of pyshtools:
  * https://pypi.python.org/simple/pyshtools/
  Getting page https://pypi.python.org/simple/pyshtools/
  Looking up "https://pypi.python.org/simple/pyshtools/" in the cache
  Current age based on date: 62489
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The cached response is "stale" with no etag, purging
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/pyshtools/ HTTP/1.1" 200 244
  Updating cache with response from "https://pypi.python.org/simple/pyshtools/"
  Caching b/c date exists and max-age > 0
  Analyzing links from page https://pypi.python.org/simple/pyshtools/
    Found link https://pypi.python.org/packages/9c/e5/7fe23d6f7103cf868e8c859621
d99a2f8bb837d418d0f4a106c2aa6450a4/pyshtools-3.4.tar.gz#md5=93fa41094bea6ccc7476
b1da38d6c4ef (from https://pypi.python.org/simple/pyshtools/), version: 3.4
  Using version 3.4 (newest of versions: 3.4)
  Looking up "https://pypi.python.org/packages/9c/e5/7fe23d6f7103cf868e8c859621d
99a2f8bb837d418d0f4a106c2aa6450a4/pyshtools-3.4.tar.gz" in the cache
  Current age based on date: 97273
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 97273
  Using cached pyshtools-3.4.tar.gz
  Downloading from URL https://pypi.python.org/packages/9c/e5/7fe23d6f7103cf868e
8c859621d99a2f8bb837d418d0f4a106c2aa6450a4/pyshtools-3.4.tar.gz#md5=93fa41094bea
6ccc7476b1da38d6c4ef (from https://pypi.python.org/simple/pyshtools/)
  Running setup.py (path:C:\Users\DIJUNG~1\AppData\Local\Temp\pip-build-ho6mmwxv
\pyshtools\setup.py) egg_info for package pyshtools
    Running command python setup.py egg_info
    no pandoc installed. Careful, pypi description will not be formatted correct
ly.
    INSTALLING SHTOOLS 3.4
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Found executable C:\MinGW\msys\1.0\bin\DF.exe
    Found executable C:\MinGW\msys\1.0\bin\DF.exe
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Found executable C:\MinGW\bin\gfortran.exe
    Found executable C:\MinGW\bin\gfortran.exe
    customize GnuFCompiler
    customize IntelVisualFCompiler
    customize AbsoftFCompiler
    customize CompaqVisualFCompiler
    customize IntelItaniumVisualFCompiler
    customize Gnu95FCompiler
    searching SHTOOLS in: build\temp.win-amd64-3.5
    non-existing path in '': 'build\\temp.win-amd64-3.5'
    non-existing path in '': 'build\\temp.win-amd64-3.5'
    running egg_info
    running build_src
    build_src
    building library "SHTOOLS" sources
    building extension "pyshtools._SHTOOLS" sources
    creating build
    creating build\src.win-amd64-3.5
    creating build\src.win-amd64-3.5\src
    f2py options: ['--quiet', '--quiet']
    f2py: src\pyshtools.pyf
      adding 'build\src.win-amd64-3.5\fortranobject.c' to sources.
      adding 'build\src.win-amd64-3.5' to include_dirs.
    copying C:\Anaconda3\lib\site-packages\numpy\f2py\src\fortranobject.c -> bui
ld\src.win-amd64-3.5
    copying C:\Anaconda3\lib\site-packages\numpy\f2py\src\fortranobject.h -> bui
ld\src.win-amd64-3.5
      adding 'build\src.win-amd64-3.5\src\_SHTOOLS-f2pywrappers.f' to sources.
    building extension "pyshtools._constant" sources
    f2py options: ['--quiet']
    f2py:> build\src.win-amd64-3.5\pyshtools\_constantmodule.c
    creating build\src.win-amd64-3.5\pyshtools
      adding 'build\src.win-amd64-3.5\fortranobject.c' to sources.
      adding 'build\src.win-amd64-3.5' to include_dirs.
      adding 'build\src.win-amd64-3.5\pyshtools\_constant-f2pywrappers2.f90' to
sources.
    build_src: building npy-pkg config files
    creating pip-egg-info\pyshtools.egg-info
    writing pip-egg-info\pyshtools.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\pyshtools.egg-info\dependency_links
.txt
    writing top-level names to pip-egg-info\pyshtools.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\pyshtools.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info\pyshtools.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info\pyshtools.egg-info\SOURCES.txt'
  Source in c:\users\dijung~1\appdata\local\temp\pip-build-ho6mmwxv\pyshtools ha
s version 3.4, which satisfies requirement pyshtools from https://pypi.python.or
g/packages/9c/e5/7fe23d6f7103cf868e8c859621d99a2f8bb837d418d0f4a106c2aa6450a4/py
shtools-3.4.tar.gz#md5=93fa41094bea6ccc7476b1da38d6c4ef
Building wheels for collected packages: pyshtools
  Running setup.py bdist_wheel for pyshtools ...   Destination directory: C:\Use
rs\DIJUNG~1\AppData\Local\Temp\tmp53nwhw8rpip-wheel-
  Running command C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__f
ile__='C:\\Users\\DIJUNG~1\\AppData\\Local\\Temp\\pip-build-ho6mmwxv\\pyshtools\
\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace
('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d C:\Users\DIJUNG~1\AppData\Loc
al\Temp\tmp53nwhw8rpip-wheel- --python-tag cp35
  no pandoc installed. Careful, pypi description will not be formatted correctly
.
  INSTALLING SHTOOLS 3.4
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Found executable C:\MinGW\msys\1.0\bin\DF.exe
  Found executable C:\MinGW\msys\1.0\bin\DF.exe
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Found executable C:\MinGW\bin\gfortran.exe
  Found executable C:\MinGW\bin\gfortran.exe
  customize GnuFCompiler
  customize IntelVisualFCompiler
  customize AbsoftFCompiler
  customize CompaqVisualFCompiler
  customize IntelItaniumVisualFCompiler
  customize Gnu95FCompiler
  searching SHTOOLS in: build\temp.win-amd64-3.5
  non-existing path in '': 'build\\temp.win-amd64-3.5'
  non-existing path in '': 'build\\temp.win-amd64-3.5'
  running bdist_wheel
  running build
  ---- BUILDING ----
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler op
tions
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler o
ptions
  running build_src
  build_src
  building library "SHTOOLS" sources
  building extension "pyshtools._SHTOOLS" sources
  f2py options: ['--quiet', '--quiet']
    adding 'build\src.win-amd64-3.5\fortranobject.c' to sources.
    adding 'build\src.win-amd64-3.5' to include_dirs.
    adding 'build\src.win-amd64-3.5\src\_SHTOOLS-f2pywrappers.f' to sources.
  building extension "pyshtools._constant" sources
  f2py options: ['--quiet']
    adding 'build\src.win-amd64-3.5\fortranobject.c' to sources.
    adding 'build\src.win-amd64-3.5' to include_dirs.
    adding 'build\src.win-amd64-3.5\pyshtools\_constant-f2pywrappers2.f90' to so
urces.
  build_src: building npy-pkg config files
  running build_py
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\pyshtools
  copying pyshtools\constant.py -> build\lib.win-amd64-3.5\pyshtools
  copying pyshtools\expand.py -> build\lib.win-amd64-3.5\pyshtools
  copying pyshtools\gravmag.py -> build\lib.win-amd64-3.5\pyshtools
  copying pyshtools\legendre.py -> build\lib.win-amd64-3.5\pyshtools
  copying pyshtools\localizedspectralanalysis.py -> build\lib.win-amd64-3.5\pysh
tools
  copying pyshtools\make_docs.py -> build\lib.win-amd64-3.5\pyshtools
  copying pyshtools\other.py -> build\lib.win-amd64-3.5\pyshtools
  copying pyshtools\rotate.py -> build\lib.win-amd64-3.5\pyshtools
  copying pyshtools\shclasses.py -> build\lib.win-amd64-3.5\pyshtools
  copying pyshtools\shio.py -> build\lib.win-amd64-3.5\pyshtools
  copying pyshtools\spectralanalysis.py -> build\lib.win-amd64-3.5\pyshtools
  copying pyshtools\__init__.py -> build\lib.win-amd64-3.5\pyshtools
  running build_clib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying fro
m distutils
  customize MSVCCompiler
  customize MSVCCompiler using build_clib
  customize GnuFCompiler
  customize IntelVisualFCompiler
  customize AbsoftFCompiler
  customize CompaqVisualFCompiler
  customize IntelItaniumVisualFCompiler
  customize Gnu95FCompiler
  customize Gnu95FCompiler
  customize Gnu95FCompiler using build_clib
  building 'SHTOOLS' library
  creating build\temp.win-amd64-3.5
  compiling Fortran 90 module sources
  Fortran f77 compiler: C:\MinGW\bin\gfortran.exe -Wall -g -ffixed-form -fno-sec
ond-underscore -O0
  Fortran f90 compiler: C:\MinGW\bin\gfortran.exe -Wall -g -fno-second-underscor
e -O0
  Fortran fix compiler: C:\MinGW\bin\gfortran.exe -Wall -g -ffixed-form -fno-sec
ond-underscore -Wall -g -fno-second-underscore -O0
  creating build\temp.win-amd64-3.5\src
  compile options: '-IC:\Anaconda3\lib\site-packages\numpy\core\include -c'
  extra options: '-Jbuild\temp.win-amd64-3.5 -Ibuild\temp.win-amd64-3.5'
  gfortran.exe:f90: src\FFTW3.f95
  gfortran.exe:f90: src\SHTOOLS.f95
  compiling Fortran sources
  Fortran f77 compiler: C:\MinGW\bin\gfortran.exe -Wall -g -ffixed-form -fno-sec
ond-underscore -O0
  Fortran f90 compiler: C:\MinGW\bin\gfortran.exe -Wall -g -fno-second-underscor
e -O0
  Fortran fix compiler: C:\MinGW\bin\gfortran.exe -Wall -g -ffixed-form -fno-sec
ond-underscore -Wall -g -fno-second-underscore -O0
  compile options: '-IC:\Anaconda3\lib\site-packages\numpy\core\include -c'
  extra options: '-Jbuild\temp.win-amd64-3.5 -Ibuild\temp.win-amd64-3.5'
  gfortran.exe:f90: src\BAtoHilm.f95
  gfortran.exe:f90: src\BAtoHilmRhoH.f95
  gfortran.exe:f90: src\CilmMinus.f95

# So I close the notification window. It continues the following process, and my python stops working again
error
  Failed building wheel for pyshtools
  Running setup.py clean for pyshtools
  Running command C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__f
ile__='C:\\Users\\DIJUNG~1\\AppData\\Local\\Temp\\pip-build-ho6mmwxv\\pyshtools\
\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace
('\r\n', '\n'), __file__, 'exec'))" clean --all
  no pandoc installed. Careful, pypi description will not be formatted correctly
.
  INSTALLING SHTOOLS 3.4
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Found executable C:\MinGW\msys\1.0\bin\DF.exe
  Found executable C:\MinGW\msys\1.0\bin\DF.exe
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Found executable C:\MinGW\bin\gfortran.exe
  Found executable C:\MinGW\bin\gfortran.exe
  customize GnuFCompiler
  customize IntelVisualFCompiler
  customize AbsoftFCompiler
  customize CompaqVisualFCompiler
  customize IntelItaniumVisualFCompiler
  customize Gnu95FCompiler
  searching SHTOOLS in: build\temp.win-amd64-3.5
  running clean
  removing 'build\temp.win-amd64-3.5' (and everything under it)
  removing 'build\lib.win-amd64-3.5' (and everything under it)
  'build\bdist.win-amd64' does not exist -- can't clean it
  'build\scripts.win-amd64-3.5' does not exist -- can't clean it
Failed to build pyshtools
Installing collected packages: pyshtools
  Running setup.py install for pyshtools ...     Running command C:\Anaconda3\py
thon.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\DIJUNG~1\\AppDa
ta\\Local\\Temp\\pip-build-ho6mmwxv\\pyshtools\\setup.py';exec(compile(getattr(t
okenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec')
)" install --record C:\Users\DIJUNG~1\AppData\Local\Temp\pip-nj3dqjav-record\ins
tall-record.txt --single-version-externally-managed --compile
    no pandoc installed. Careful, pypi description will not be formatted correct
ly.
    INSTALLING SHTOOLS 3.4
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Found executable C:\MinGW\msys\1.0\bin\DF.exe
    Found executable C:\MinGW\msys\1.0\bin\DF.exe
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Found executable C:\MinGW\bin\gfortran.exe
    Found executable C:\MinGW\bin\gfortran.exe
    customize GnuFCompiler
    customize IntelVisualFCompiler
    customize AbsoftFCompiler
    customize CompaqVisualFCompiler
    customize IntelItaniumVisualFCompiler
    customize Gnu95FCompiler
    searching SHTOOLS in: build\temp.win-amd64-3.5
    non-existing path in '': 'build\\temp.win-amd64-3.5'
    non-existing path in '': 'build\\temp.win-amd64-3.5'
    running install
    ---- CUSTOM INSTALL ----
    running build
    ---- BUILDING ----
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler
options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler
 options
    running build_src
    build_src
    building library "SHTOOLS" sources
    building extension "pyshtools._SHTOOLS" sources
    f2py options: ['--quiet', '--quiet']
      adding 'build\src.win-amd64-3.5\fortranobject.c' to sources.
      adding 'build\src.win-amd64-3.5' to include_dirs.
      adding 'build\src.win-amd64-3.5\src\_SHTOOLS-f2pywrappers.f' to sources.
    building extension "pyshtools._constant" sources
    f2py options: ['--quiet']
      adding 'build\src.win-amd64-3.5\fortranobject.c' to sources.
      adding 'build\src.win-amd64-3.5' to include_dirs.
      adding 'build\src.win-amd64-3.5\pyshtools\_constant-f2pywrappers2.f90' to
sources.
    build_src: building npy-pkg config files
    running build_py
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\pyshtools
    copying pyshtools\constant.py -> build\lib.win-amd64-3.5\pyshtools
    copying pyshtools\expand.py -> build\lib.win-amd64-3.5\pyshtools
    copying pyshtools\gravmag.py -> build\lib.win-amd64-3.5\pyshtools
    copying pyshtools\legendre.py -> build\lib.win-amd64-3.5\pyshtools
    copying pyshtools\localizedspectralanalysis.py -> build\lib.win-amd64-3.5\py
shtools
    copying pyshtools\make_docs.py -> build\lib.win-amd64-3.5\pyshtools
    copying pyshtools\other.py -> build\lib.win-amd64-3.5\pyshtools
    copying pyshtools\rotate.py -> build\lib.win-amd64-3.5\pyshtools
    copying pyshtools\shclasses.py -> build\lib.win-amd64-3.5\pyshtools
    copying pyshtools\shio.py -> build\lib.win-amd64-3.5\pyshtools
    copying pyshtools\spectralanalysis.py -> build\lib.win-amd64-3.5\pyshtools
    copying pyshtools\__init__.py -> build\lib.win-amd64-3.5\pyshtools
    running build_clib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying f
rom distutils
    customize MSVCCompiler
    customize MSVCCompiler using build_clib
    customize GnuFCompiler
    customize IntelVisualFCompiler
    customize AbsoftFCompiler
    customize CompaqVisualFCompiler

# I close the notification again, and it goes like this
error
Cleaning up...
  Removing source in C:\Users\DIJUNG~1\AppData\Local\Temp\pip-build-ho6mmwxv\pys
htools
Command "C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:
\\Users\\DIJUNG~1\\AppData\\Local\\Temp\\pip-build-ho6mmwxv\\pyshtools\\setup.py
';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n',
'\n'), __file__, 'exec'))" install --record C:\Users\DIJUNG~1\AppData\Local\Temp
\pip-nj3dqjav-record\install-record.txt --single-version-externally-managed --co
mpile" failed with error code 255 in C:\Users\DIJUNG~1\AppData\Local\Temp\pip-bu
ild-ho6mmwxv\pyshtools\
Exception information:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\pip-8.1.2-py3.5.egg\pip\basecommand.py",
line 215, in main
    status = self.run(options, args)
  File "C:\Anaconda3\lib\site-packages\pip-8.1.2-py3.5.egg\pip\commands\install.
py", line 317, in run
    prefix=options.prefix_path,
  File "C:\Anaconda3\lib\site-packages\pip-8.1.2-py3.5.egg\pip\req\req_set.py",
line 742, in install
    **kwargs
  File "C:\Anaconda3\lib\site-packages\pip-8.1.2-py3.5.egg\pip\req\req_install.p
y", line 880, in install
    spinner=spinner,
  File "C:\Anaconda3\lib\site-packages\pip-8.1.2-py3.5.egg\pip\utils\__init__.py
", line 718, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "C:\Anaconda3\python.exe -u -c "import
 setuptools, tokenize;__file__='C:\\Users\\DIJUNG~1\\AppData\\Local\\Temp\\pip-b
uild-ho6mmwxv\\pyshtools\\setup.py';exec(compile(getattr(tokenize, 'open', open)
(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:
\Users\DIJUNG~1\AppData\Local\Temp\pip-nj3dqjav-record\install-record.txt --sing
le-version-externally-managed --compile" failed with error code 255 in C:\Users\
DIJUNG~1\AppData\Local\Temp\pip-build-ho6mmwxv\pyshtools\

**Comment by ioshchepkov** [comment]
I'm definitely not a Windows guy, but I found something. If you didn't yet, try to create in `PYTHONPATH\Lib\distutils` a file `distutils.cfg` with this
```
[build]
compiler=mingw32
```

**Comment by Dijun-G** [comment]
Thank you, but doesn't work.

**Comment by MarkWieczorek** [comment]
Hi Dijun, I'm a little confused by all of this output (I didn't write the setup.py file.). Could you first try to compile only the fortran part of SHTOOLS? If you can't get this to work, the python part certaintly won't work either.

First, just use
```
make fortran
```
You might need to add options like
```
make fortran F95='name-of-my compiler' F95FLAGS='my-compiler-flags'
```
See the documenation on installing for advice on how to set these parameters.

Then, try to run the fortran examples
```
make fortran-tests
```
When we figure out the options for `F95` and `F95FLAGS`, I will hard code them into the make files.

**Comment by Dijun-G** [comment]
Hi Mark,
The setup.py is actually included in the packages. If I install it using pip, it may run from setup.py.
Unfortunately, I cannot compile fortran successfully on my machine. The following is the results of running
`make fortran`,
_process_begin: CreateProcess(NULL, python3 -c "import sysconfig; print(sysconfig
.get_path(\"platlib\"))", ...) failed.
process_begin: CreateProcess(NULL, python3 -c "import sysconfig; print(sysconfig
.get_config_var(\"SO\"))", ...) failed.
mkdir -pv lib
A subdirectory or file -pv already exists.
Error occurred while processing: -pv.
A subdirectory or file lib already exists.
Error occurred while processing: lib.
Makefile:218: recipe for target 'fortran' failed
make: *** [fortran] Error 1_

and the other commands cannot compile right either.

**Besides, do FFTW, LAPACK and BLAS need to be installed before installing SHTOOLS?**

**Comment by MarkWieczorek** [comment]
In order to use SHTOOLS, you need to have a fortran compiler and also have installed FFTW and LAPACK (or equivalent).

As for the errors, I don't understand why `mkdir -pv` doesn't work on windows. Here is what the man page says for this option
```
 -p      Create intermediate directories as required.  If this option is not specified, the full path prefix of each operand must already exist.  On the other hand, with this option specified, no error will be reported if a directory given as an operand already exists.  Intermediate directories are created with permission bits of rwxrwxrwx (0777) as modified by the current umask, plus write and search permission for the owner.
```
What does `man mkdir` say on your machine?

**Comment by MarkWieczorek** [comment]
I would imagine that this can be installed in Windows, so if you ever make progress, let me know so that I can update the instruction. In any case, I'm glad to hear that it works on linux for you.

**Comment by MarkWieczorek** [comment]
Hi there. We have just built our first binary wheel for windows. Would you be interested in testing it? If so, use 

```pip install pyshtools==4.1
```
The current version is 4.1.1, and once we test all the wheels, we will upload them to 4.1.1...
