### ISSUE TITLE
MakeGravGridDH Bug with EGM2008 coefficients?

### ISSUE THREAD

**Issue by fghorow** [SHTOOLS/SHTOOLS#90]
I think that I might either:
1) have found a bug in (the Python binding to?) MakeGravGridDH when using the EGM2008 gravity coefficients,
or
2) not understand how to call MakeGravGridH correctly to remove the normal gravity and generate the disturbing potential T.

A Jupyter notebook documenting my attempts is publicly available at <https://github.com/fghorow/SHToolsDemo/blob/master/SHToolsMakeGravGridBug.ipynb>.

I am (of course) ready to test any suggestions/modifications you might have.

I would greatly appreciate any help you might be able to provide to solve this issue! 

Many Thanks!
Frank Horowitz
Cornell University

**Comment by MarkWieczorek** [comment]
Thanks for making the notebook: The first thing I learned about was MapDrawer. We are looking for a good map projection routine, and being frustrated with installing Cartopy, maybe this is a good contender!

As for the question. If I understand properly, the problem is that the value of POT that comes out of MakeGravGridDH is not what you expect it to be. This is probably related to geophysicists and geodesists doing things somewhat differently, me doing something stupid, or EGM08 not setting the degree 0 term to 1. So let me tell you what it actually is, and then I can change it (or the man pages) accordingly later. 

According to my code, POT is a combination of two things:
1. The full gravitational potential calculated on the flattened ellipsoid using the input spherical harmonic coefficients. This includes the degree 0 term, and C00 should be 1 when `omega` and `f` are set.
2. The psuedo-rotational potential, also calculated on the flattened ellipsoid.

Now, there are a couple of things that might be wrong. 
-The C00 term should be set to 1, but my version of the EGM08 coefficients starts at degree 2. My code *should* complain if c00 is not 1, but maybe this is not being flagged correctly.
- The `geoid` is calculated with respect to a flattened ellipsoid, but the potential you compare it to is the full potential. I would need to think about this more, and I don't have time to think today...

So, let me know if you are still having problems. If it is a bug, I will track it down. If what I am calling the potential is not what you expect it to be, at a minimum, I will make this more clear in the man pages.

**Comment by fghorow** [comment]
MapDrawer was my own hack, so I could get it right once-and-only-once and forget about it. The code is in the same Github repo as the demo notebook. I licensed it 2-clause BSD, but if you find it useful and wish to grab it, that is completely negotiable, and I am quite willing to re-license. (It's only about a page of code, all up.)
I'll chase down the C00=1 stuff for the potential. 
Thanks for looking in to this when you have the time!

**Comment by MarkWieczorek** [comment]
It turns out that the degree 0 term is the problem.

I ran this in a python notebook and got the same output as you. I knew that EGM08 didn't set the degree 0 term, and I was wondering why my code didn't complain. 

So, I re-ran this in the terminal and got the following output:

>  Warning --- MakeGravGridDH
 The degree-0 term of the spherical harmonic coefficients is not equal to 1.
 The variation in gravity resulting from variations in radius of the flattened ellipsoid will not be taken into account.
 C00 =    0.0000000000000000     
 F =    3.3528106647474805E-003

I don't know why the notebook didn't output this message (which is just a print statement in the Fortran code).

Do you have any suggestions? I'd prefer not hard coding the degree 0 term to 1...

**Comment by fghorow** [comment]
Regarding suggestions, I'd need to get deeper into the guts of using f2py (I think) to wrap your F95 code. 
The [notebook](https://github.com/fghorow/SHToolsDemo/blob/master/SHToolsMakeGravGridBug.ipynb) now shows what happens to all the outputs from MakeGravGridDH with and without C00=1.0. (The older version is in the release tagged v0.0.1-alpha, while this version is in v0.0.2-alpha...)

**Comment by MarkWieczorek** [comment]
I'm not sure what the problem is, as it appears to be working for me. Could you run this [notebook](https://gist.github.com/MarkWieczorek/26a13543186a2ad4aa8dd0d371cc50f0) and let me know if you get the same results? Also, are you running the latest version 4.1?

**Comment by fghorow** [comment]
Yes, I am running 4.0. Running your notebook in my setup gives [results](https://github.com/fghorow/SHToolsDemo/blob/master/Plot_EGM08.ipynb) similar to yours (modulo default image sizes, and color palette). 
I think this might be a case of using the direct Fortran bindings (like in my original notebook) causing some issues, but going through the more Pythonic interface working. If I were better at debugging f2py wrapped code, I'd wade in and try to find what's happening, but (as usual) life intrudes.
One last question: to get rid of the rotational contribution to the potential, do I simply set omega to zero, or is there something else I need to do? I'm basically after the "disturbing potential, T" (according to geodesists, the potential due solely to mass density contrasts in the interior of the planet). That's what I thought I was approximating via Brun's formula in my original notebook...

**Comment by fghorow** [comment]
OK. It's a bug somewhere in my MapDrawer class. When I try to plot the stuff that plotted correctly with your code, it showed the same terrible result as in my original notebook. I'll chase that down ASAP, and post the corrected code to my SHToolsDemo repository.
Sorry to send you off on such a wild goose chase... :-(
And, thank you VERY MUCH for all of your help!

**Comment by MarkWieczorek** [comment]
A potential problem might be that the DH grids don't have any data for the south Pole, 90S. Maybe these are getting set to random numbers which are screwing up your color scale limits?  This particularity is something that bothers me, and I'm going to fix this in the future.
