### ISSUE TITLE
Package for Arch linux in the Arch User Repository

### ISSUE THREAD

**Issue by strawpants** [SHTOOLS/SHTOOLS#96]
For your interest: I build a package (fortran version only of 4.0) in the [Arch User Repository](https://aur.archlinux.org/packages/shtools-fortran/). 
I still needed to apply a [patch](https://aur.archlinux.org/cgit/aur.git/tree/ChangeF90stops.patch?h=shtools-fortran) in order to have gfortran stop complaining about failing spaces behind stop statements (2 files affected). But maybe this has been solved already in the developer version?

**Comment by MarkWieczorek** [comment]
Could you make the changes that are causing problems on the develop branch and open a pull request? (I could do this too, but I am a bit busy right now...) I would be really happy to have this available on archlinux. Also, let me know if there is anything else that should be changed to make this easier for you.

**Comment by strawpants** [comment]
Done. Only one file remained affected by this in the developer branch (and only in the testsuite). Arch package seems to be fine. I'll try to let it track the main releases.

**Comment by MarkWieczorek** [comment]
I figured out the problem: That file was really old and had lots of extra tabs in it. The problem was not the lack of a space, but that there was a tab immediately after the stop. I cleaned up the file, and  will merge this with my own repo. I'm just going to close this issue for now.

For info, I will try to put out a new release with all these changes in about 1 months time.
